version: "3"
services:
  HubService:
    image: selenium/hub:4.0.0-rc-2-20210930
    container_name: seleniumHub
    ports:
      - "4445:4444" 
      - "4442:4442"
      - "4443:4443"

  ChromeService:
    image: selenium/node-chrome:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    depends_on:
      - HubService   
    volumes:
      - /dev/shm:/dev/shm
      - ./videos:/videos
    command: >
      sh -c "SE_NODE_MAX_SESSIONS=3
             SE_NODE_VIDEO=true
             SE_NODE_VIDEO_OUTPUT_DIR=/videos
             SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
             SE_NODE_VIDEO_CODEC=vp9
             SE_NODE_VIDEO_FRAMERATE=24
             SE_NODE_VIDEO_RESOLUTION=1920x1080
             SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
             SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
             /opt/bin/entry_point.sh"
 
  FirefoxService:
    image: selenium/node-firefox:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    depends_on:
      - HubService  
    volumes:
      - /dev/shm:/dev/shm
      - ./videos:/videos
    command: >
      sh -c "SE_NODE_MAX_SESSIONS=2
             SE_NODE_VIDEO=true
             SE_NODE_VIDEO_OUTPUT_DIR=/videos
             SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
             SE_NODE_VIDEO_CODEC=vp9
             SE_NODE_VIDEO_FRAMERATE=24
             SE_NODE_VIDEO_RESOLUTION=1920x1080
             SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
             SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
             /opt/bin/entry_point.sh"

  EdgeService:
    image: selenium/node-edge:4.0.0-rc-2-20210930
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    depends_on:
      - HubService
    volumes:
      - /dev/shm:/dev/shm
      - ./videos:/videos
    command: >
      sh -c "SE_NODE_MAX_SESSIONS=2
             SE_NODE_VIDEO=true
             SE_NODE_VIDEO_OUTPUT_DIR=/videos
             SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
             SE_NODE_VIDEO_CODEC=vp9
             SE_NODE_VIDEO_FRAMERATE=24
             SE_NODE_VIDEO_RESOLUTION=1920x1080
             SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
             SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
             /opt/bin/entry_point.sh"

# bu docker-compose dosyasını -f parametresi ile çalıştırıyoruz.
# docker-compose -f seleniumgridyoutube.yml up -d