# https://www.youtube.com/watch?v=NjQ5zZM7fpI
# https://www.youtube.com/watch?v=r1gdJ-QICmY

version: "3"
services:
  HubService:
    image: selenium/hub:latest
    container_name: seleniumHub
    ports:
      - "4445:4444" 
      - "4442:4442"
      - "4443:4443"

  ChromeService:
    image: selenium/node-chrome:latest
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
    depends_on:
      - HubService   
    # volumes:
    #   - /dev/shm:/dev/shm
    #   - ./videos:/videos
    # command: >
    #   sh -c "SE_NODE_MAX_SESSIONS=3
    #          SE_NODE_VIDEO=true
    #          SE_NODE_VIDEO_OUTPUT_DIR=/videos
    #          SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
    #          SE_NODE_VIDEO_CODEC=vp9
    #          SE_NODE_VIDEO_FRAMERATE=24
    #          SE_NODE_VIDEO_RESOLUTION=1920x1080
    #          SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
    #          SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
    #          /opt/bin/entry_point.sh"
 
  FirefoxService:
    image: selenium/node-firefox:latest
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    depends_on:
      - HubService  
    # volumes:
    #   - /dev/shm:/dev/shm
    #   - ./videos:/videos
    # command: >
    #   sh -c "SE_NODE_MAX_SESSIONS=2
    #          SE_NODE_VIDEO=true
    #          SE_NODE_VIDEO_OUTPUT_DIR=/videos
    #          SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
    #          SE_NODE_VIDEO_CODEC=vp9
    #          SE_NODE_VIDEO_FRAMERATE=24
    #          SE_NODE_VIDEO_RESOLUTION=1920x1080
    #          SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
    #          SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
    #          /opt/bin/entry_point.sh"

  EdgeService:
    image: selenium/node-edge:latest
    shm_size: "2gb"
    ports:
      - "5900"  
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    depends_on:
      - HubService
    # volumes:
    #   - /dev/shm:/dev/shm
    #   - ./videos:/videos
    # command: >
    #   sh -c "SE_NODE_MAX_SESSIONS=2
    #          SE_NODE_VIDEO=true
    #          SE_NODE_VIDEO_OUTPUT_DIR=/videos
    #          SE_NODE_VIDEO_OUTPUT_FILE=${SE_NODE_SESSION_NAME}.mp4
    #          SE_NODE_VIDEO_CODEC=vp9
    #          SE_NODE_VIDEO_FRAMERATE=24
    #          SE_NODE_VIDEO_RESOLUTION=1920x1080
    #          SE_NODE_VIDEO_CLEANUP_ON_EXIT=true
    #          SE_NODE_PROXY_PARAMS='--proxy-server=proxy:8080'
    #          /opt/bin/entry_point.sh"

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230920
    volumes:
      - ./TestRecordings:/videos
    depends_on:
      - ChromeService
    environment:
      - DISPLAY_CONTAINER_NAME=ChromeService
      - FILE_NAME=chrome_video.mp4

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20230920
    volumes:
      - ./TestRecordings:/videos
    depends_on:
      - EdgeService
    environment:
      - DISPLAY_CONTAINER_NAME=EdgeService
      - FILE_NAME=edge_video.mp4

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20230920
    volumes:
      - ./TestRecordings:/videos
    depends_on:
      - FirefoxService
    environment:
      - DISPLAY_CONTAINER_NAME=FirefoxService
      - FILE_NAME=firefox_video.mp4

  # VideoService:
  #   image: elgalu/selenium:latest
  #   container_name: seleniumVideo
  #   ports:
  #     - "5555:5555"
  #   volumes:
  #     - ./videos:/videos
  #   command: >
  #     sh -c "mkdir -p /videos
  #            chmod -R 777 /videos
  #            /opt/bin/entry_point.sh"

# VideoService service'inin içine bağlanmak için exec komutu : docker exec -it seleniumVideo bash